language: node_js
node_js:
- 7
- 8
- 10
before_install:
- npm install -g npm
script:
- npm install
- npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: e3274260a96640f0e23004368d84f50888c685be
  app: automate-heorku
  on:
    repo: adarabinda/automate-deployment-on-heroku
